name: 'Fargate deployment on main branch'
on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  fargate_deploy:
    name: 'Fargate Deploy'
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Docker Login'
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin 150770890717.dkr.ecr.ap-northeast-1.amazonaws.com/internship_aug2022_2
      - name: 'Build Application image'
        run: |
          docker pull 150770890717.dkr.ecr.ap-northeast-1.amazonaws.com/internship_aug2022_2:build-cache || true
          docker build . -f Dockerfile.production -t internship_aug2022_2 --cache-from 150770890717.dkr.ecr.ap-northeast-1.amazonaws.com/internship_aug2022_2:build-cache --build-arg RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
      - name: 'Push Application image'
        run: |
          docker tag internship_aug2022_2:latest 150770890717.dkr.ecr.ap-northeast-1.amazonaws.com/internship_aug2022_2:latest
          docker push 150770890717.dkr.ecr.ap-northeast-1.amazonaws.com/internship_aug2022_2:latest
          docker tag internship_aug2022_2:latest 150770890717.dkr.ecr.ap-northeast-1.amazonaws.com/internship_aug2022_2:build-cache
          docker push 150770890717.dkr.ecr.ap-northeast-1.amazonaws.com/internship_aug2022_2:build-cache
      - name: 'Run migration task'
        id: migration-task
        run: |
          echo "::set-output name=migration-task-id::$(aws ecs run-task --cluster internship-aug2022-2 --task-definition internship-aug2022-2-migration --launch-type FARGATE --network-configuration '{"awsvpcConfiguration":{"subnets":["subnet-0334f01a7f2e84910","subnet-06e60f8f517606654","subnet-0df45f1bdece2446d"],"securityGroups": ["sg-0ee03f05942978041"],"assignPublicIp":"ENABLED"}}' --count 1 | jq -r '.tasks[0].taskArn')"
      - name: 'Wait for migration task to finish'
        run: |
          aws ecs wait tasks-stopped --cluster internship-aug2022-2 --tasks "${{ steps.migration-task.outputs.migration-task-id }}"
          exit $(aws ecs describe-tasks --cluster internship-aug2022-2 --tasks "${{ steps.migration-task.outputs.migration-task-id }}" | jq -r '.tasks[0].containers[0].exitCode')
      - name: 'Update ECS service'
        run: |
          aws ecs update-service --cluster internship-aug2022-2 --service internship-aug2022-2 --task-definition internship-aug2022-2 --force-new-deployment
      - name: 'Wait for ECS service deployment'
        run: |
          aws ecs wait services-stable --cluster internship-aug2022-2 --service internship-aug2022-2
